server:
  port: 8082
  servlet:
    context-path: /my
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC

#阿里云短信发送
aliyun:
  message:
    region_id: default
    access_key_id: xxxxxx
    secret: f6W3Q3nyq1G7haF403iJSiXL9y0muy
    template_code: SMS_160861359
    sign_name: ͬ统一用户管理系统

#腾讯云短信发送参数
tencent:
  app_id: 1400194981
  app_key: db90e9646ce1392ed9a95ade41f9bff9
  sms_sign: 同方股份有限公司
  template_id: 311233
